from typing import Final

# TODO add more languages
class Languages:
    """ Enum with YouTube-supported localisations """
    EN    :Final[str] = "en"    # English
    AR    :Final[str] = "ar"    # Arabic
    ES_US :Final[str] = "es-us" # Spanish
    FR    :Final[str] = "fr"    # French
    DE    :Final[str] = "de"    # German
    AF    :Final[str] = "af"    # African
    PT    :Final[str] = "pt-pt" # Portuguese
    MN    :Final[str] = "mn"    # Mongolian
    RU    :Final[str] = "ru"    # Russian
    UK    :Final[str] = "uk"    # Ukrainian
    BE    :Final[str] = "be"    # Belarusian
    SR    :Final[str] = "sr"    # Serbian
    NL    :Final[str] = "nl"    # Dutch
    TR    :Final[str] = "tr"    # Turkish

class AccountTypes:
    """ Enum with account types for channels """
    REGULAR  :Final[str] = "regular"  # just regular account type
    ARTIST   :Final[str] = "artist"   # verified music artist
    VERIFIED :Final[str] = "verified" # verified account type

class Regions:
    """ Class serving YouTube-supported regions """
    US :Final[str] = "US" # United States
    AD :Final[str] = "AD" # Andorra
    AE :Final[str] = "AE" # United Arab Emirates
    AF :Final[str] = "AF" # Afghanistan
    AG :Final[str] = "AG" # Antigua and Barbuda
    AI :Final[str] = "AI" # Anguilla
    AL :Final[str] = "AL" # Albania
    AM :Final[str] = "AM" # Armenia
    AO :Final[str] = "AO" # Angola
    AQ :Final[str] = "AQ" # Antarctica
    AR :Final[str] = "AR" # Argentina
    AS :Final[str] = "AS" # American Samoa
    AT :Final[str] = "AT" # Austria
    AU :Final[str] = "AU" # Australia
    AW :Final[str] = "AW" # Aruba
    AX :Final[str] = "AX" # Åland Islands
    AZ :Final[str] = "AZ" # Azerbaijan
    BA :Final[str] = "BA" # Bosnia and Herzegovina
    BB :Final[str] = "BB" # Barbados
    BD :Final[str] = "BD" # Bangladesh
    BE :Final[str] = "BE" # Belgium
    BF :Final[str] = "BF" # Burkina Faso
    BG :Final[str] = "BG" # Bulgaria
    BH :Final[str] = "BH" # Bahrain
    BI :Final[str] = "BI" # Burundi
    BJ :Final[str] = "BJ" # Benin
    BL :Final[str] = "BL" # Saint Barthélemy
    BM :Final[str] = "BM" # Bermuda
    BN :Final[str] = "BN" # Brunei Darussalam
    BO :Final[str] = "BO" # Bolivia
    BQ :Final[str] = "BQ" # Bonaire, Sint Eustatius and Saba
    BR :Final[str] = "BR" # Brazil
    BS :Final[str] = "BS" # Bahamas
    BT :Final[str] = "BT" # Bhutan
    BV :Final[str] = "BV" # Bouvet Island
    BW :Final[str] = "BW" # Botswana
    BY :Final[str] = "BY" # Belarus
    BZ :Final[str] = "BZ" # Belize
    CA :Final[str] = "CA" # Canada
    CC :Final[str] = "CC" # Cocos (Keeling) Islands
    CD :Final[str] = "CD" # Congo, Democratic Republic of the
    CF :Final[str] = "CF" # Central African Republic
    CG :Final[str] = "CG" # Congo
    CH :Final[str] = "CH" # Switzerland
    CI :Final[str] = "CI" # Côte d'Ivoire
    CK :Final[str] = "CK" # Cook Islands
    CL :Final[str] = "CL" # Chile
    CM :Final[str] = "CM" # Cameroon
    CN :Final[str] = "CN" # China
    CO :Final[str] = "CO" # Colombia
    CR :Final[str] = "CR" # Costa Rica
    CU :Final[str] = "CU" # Cuba
    CV :Final[str] = "CV" # Cabo Verde
    CW :Final[str] = "CW" # Curaçao
    CX :Final[str] = "CX" # Christmas Island
    CY :Final[str] = "CY" # Cyprus
    CZ :Final[str] = "CZ" # Czechia
    DE :Final[str] = "DE" # Germany
    DJ :Final[str] = "DJ" # Djibouti
    DK :Final[str] = "DK" # Denmark
    DM :Final[str] = "DM" # Dominica
    DO :Final[str] = "DO" # Dominican Republic
    DZ :Final[str] = "DZ" # Algeria
    EC :Final[str] = "EC" # Ecuador
    EE :Final[str] = "EE" # Estonia
    EG :Final[str] = "EG" # Egypt
    EH :Final[str] = "EH" # Western Sahara
    ER :Final[str] = "ER" # Eritrea
    ES :Final[str] = "ES" # Spain
    ET :Final[str] = "ET" # Ethiopia
    FI :Final[str] = "FI" # Finland
    FJ :Final[str] = "FJ" # Fiji
    FK :Final[str] = "FK" # Falkland Islands (Malvinas)
    FM :Final[str] = "FM" # Micronesia
    FO :Final[str] = "FO" # Faroe Islands
    FR :Final[str] = "FR" # France
    GA :Final[str] = "GA" # Gabon
    GB :Final[str] = "GB" # United Kingdom
    GD :Final[str] = "GD" # Grenada
    GE :Final[str] = "GE" # Georgia
    GF :Final[str] = "GF" # French Guiana
    GG :Final[str] = "GG" # Guernsey
    GH :Final[str] = "GH" # Ghana
    GI :Final[str] = "GI" # Gibraltar
    GL :Final[str] = "GL" # Greenland
    GM :Final[str] = "GM" # Gambia
    GN :Final[str] = "GN" # Guinea
    GP :Final[str] = "GP" # Guadeloupe
    GQ :Final[str] = "GQ" # Equatorial Guinea
    GR :Final[str] = "GR" # Greece
    GS :Final[str] = "GS" # South Georgia and the South Sandwich Islands
    GT :Final[str] = "GT" # Guatemala
    GU :Final[str] = "GU" # Guam
    GW :Final[str] = "GW" # Guinea-Bissau
    GY :Final[str] = "GY" # Guyana
    HK :Final[str] = "HK" # Hong Kong
    HM :Final[str] = "HM" # Heard Island and McDonald Islands
    HN :Final[str] = "HN" # Honduras
    HR :Final[str] = "HR" # Croatia
    HT :Final[str] = "HT" # Haiti
    HU :Final[str] = "HU" # Hungary
    ID :Final[str] = "ID" # Indonesia
    IE :Final[str] = "IE" # Ireland
    IL :Final[str] = "IL" # Israel
    IM :Final[str] = "IM" # Isle of Man
    IN :Final[str] = "IN" # India
    IO :Final[str] = "IO" # British Indian Ocean Territory
    IQ :Final[str] = "IQ" # Iraq
    IR :Final[str] = "IR" # Iran
    IS :Final[str] = "IS" # Iceland
    IT :Final[str] = "IT" # Italy
    JE :Final[str] = "JE" # Jersey
    JM :Final[str] = "JM" # Jamaica
    JO :Final[str] = "JO" # Jordan
    JP :Final[str] = "JP" # Japan
    KE :Final[str] = "KE" # Kenya
    KG :Final[str] = "KG" # Kyrgyzstan
    KH :Final[str] = "KH" # Cambodia
    KI :Final[str] = "KI" # Kiribati
    KM :Final[str] = "KM" # Comoros
    KN :Final[str] = "KN" # Saint Kitts and Nevis
    KP :Final[str] = "KP" # Korea (Democratic People's Republic of)
    KR :Final[str] = "KR" # Korea, Republic of
    KW :Final[str] = "KW" # Kuwait
    KY :Final[str] = "KY" # Cayman Islands
    KZ :Final[str] = "KZ" # Kazakhstan
    LA :Final[str] = "LA" # Lao People's Democratic Republic
    LB :Final[str] = "LB" # Lebanon
    LC :Final[str] = "LC" # Saint Lucia
    LI :Final[str] = "LI" # Liechtenstein
    LK :Final[str] = "LK" # Sri Lanka
    LR :Final[str] = "LR" # Liberia
    LS :Final[str] = "LS" # Lesotho
    LT :Final[str] = "LT" # Lithuania
    LU :Final[str] = "LU" # Luxembourg
    LV :Final[str] = "LV" # Latvia
    LY :Final[str] = "LY" # Libya
    MA :Final[str] = "MA" # Morocco
    MC :Final[str] = "MC" # Monaco
    MD :Final[str] = "MD" # Moldova
    ME :Final[str] = "ME" # Montenegro
    MF :Final[str] = "MF" # Saint Martin (French part)
    MG :Final[str] = "MG" # Madagascar
    MH :Final[str] = "MH" # Marshall Islands
    MK :Final[str] = "MK" # North Macedonia
    ML :Final[str] = "ML" # Mali
    MM :Final[str] = "MM" # Myanmar
    MN :Final[str] = "MN" # Mongolia
    MO :Final[str] = "MO" # Macao
    MP :Final[str] = "MP" # Northern Mariana Islands
    MQ :Final[str] = "MQ" # Martinique
    MR :Final[str] = "MR" # Mauritania
    MS :Final[str] = "MS" # Montserrat
    MT :Final[str] = "MT" # Malta
    MU :Final[str] = "MU" # Mauritius
    MV :Final[str] = "MV" # Maldives
    MW :Final[str] = "MW" # Malawi
    MX :Final[str] = "MX" # Mexico
    MY :Final[str] = "MY" # Malaysia
    MZ :Final[str] = "MZ" # Mozambique
    NA :Final[str] = "NA" # Namibia
    NC :Final[str] = "NC" # New Caledonia
    NE :Final[str] = "NE" # Niger
    NF :Final[str] = "NF" # Norfolk Island
    NG :Final[str] = "NG" # Nigeria
    NI :Final[str] = "NI" # Nicaragua
    NL :Final[str] = "NL" # Netherlands
    NO :Final[str] = "NO" # Norway
    NP :Final[str] = "NP" # Nepal
    NR :Final[str] = "NR" # Nauru
    NU :Final[str] = "NU" # Niue
    NZ :Final[str] = "NZ" # New Zealand
    OM :Final[str] = "OM" # Oman
    PA :Final[str] = "PA" # Panama
    PE :Final[str] = "PE" # Peru
    PF :Final[str] = "PF" # French Polynesia
    PG :Final[str] = "PG" # Papua New Guinea
    PH :Final[str] = "PH" # Philippines
    PK :Final[str] = "PK" # Pakistan
    PL :Final[str] = "PL" # Poland
    PM :Final[str] = "PM" # Saint Pierre and Miquelon
    PN :Final[str] = "PN" # Pitcairn
    PR :Final[str] = "PR" # Puerto Rico
    PS :Final[str] = "PS" # Palestine, State of
    PT :Final[str] = "PT" # Portugal
    PW :Final[str] = "PW" # Palau
    PY :Final[str] = "PY" # Paraguay
    QA :Final[str] = "QA" # Qatar
    RE :Final[str] = "RE" # Réunion
    RO :Final[str] = "RO" # Romania
    RS :Final[str] = "RS" # Serbia
    RU :Final[str] = "RU" # Russia
    RW :Final[str] = "RW" # Rwanda
    SA :Final[str] = "SA" # Saudi Arabia
    SB :Final[str] = "SB" # Solomon Islands
    SC :Final[str] = "SC" # Seychelles
    SD :Final[str] = "SD" # Sudan
    SE :Final[str] = "SE" # Sweden
    SG :Final[str] = "SG" # Singapore
    SH :Final[str] = "SH" # Saint Helena, Ascension and Tristan da Cunha
    SI :Final[str] = "SI" # Slovenia
    SJ :Final[str] = "SJ" # Svalbard and Jan Mayen
    SK :Final[str] = "SK" # Slovakia
    SL :Final[str] = "SL" # Sierra Leone
    SM :Final[str] = "SM" # San Marino
    SN :Final[str] = "SN" # Senegal
    SO :Final[str] = "SO" # Somalia
    SR :Final[str] = "SR" # Suriname
    SS :Final[str] = "SS" # South Sudan
    ST :Final[str] = "ST" # Sao Tome and Principe
    SV :Final[str] = "SV" # El Salvador
    SX :Final[str] = "SX" # Sint Maarten (Dutch part)
    SY :Final[str] = "SY" # Syrian Arab Republic
    SZ :Final[str] = "SZ" # Eswatini
    TC :Final[str] = "TC" # Turks and Caicos Islands
    TD :Final[str] = "TD" # Chad
    TF :Final[str] = "TF" # French Southern Territories
    TG :Final[str] = "TG" # Togo
    TH :Final[str] = "TH" # Thailand
    TJ :Final[str] = "TJ" # Tajikistan
    TK :Final[str] = "TK" # Tokelau
    TL :Final[str] = "TL" # Timor-Leste
    TM :Final[str] = "TM" # Turkmenistan
    TN :Final[str] = "TN" # Tunisia
    TO :Final[str] = "TO" # Tonga
    TR :Final[str] = "TR" # Turkey
    TT :Final[str] = "TT" # Trinidad and Tobago
    TV :Final[str] = "TV" # Tuvalu
    TW :Final[str] = "TW" # Taiwan, Province of China
    TZ :Final[str] = "TZ" # Tanzania, United Republic of
    UA :Final[str] = "UA" # Ukraine
    UG :Final[str] = "UG" # Uganda
    UM :Final[str] = "UM" # United States Minor Outlying Islands
    US :Final[str] = "US" # United States
    UY :Final[str] = "UY" # Uruguay
    UZ :Final[str] = "UZ" # Uzbekistan
    VA :Final[str] = "VA" # Holy See
    VC :Final[str] = "VC" # Saint Vincent and the Grenadines
    VE :Final[str] = "VE" # Venezuela
    VG :Final[str] = "VG" # Virgin Islands (British)
    VI :Final[str] = "VI" # Virgin Islands (U.S.)
    VN :Final[str] = "VN" # Viet Nam
    VU :Final[str] = "VU" # Vanuatu
    WF :Final[str] = "WF" # Wallis and Futuna
    WS :Final[str] = "WS" # Samoa
    YE :Final[str] = "YE" # Yemen
    YT :Final[str] = "YT" # Mayotte
    ZA :Final[str] = "ZA" # South Africa
    ZM :Final[str] = "ZM" # Zambia
    ZW :Final[str] = "ZW" # Zimbabwe